kind = "web"
previewPath = "/"
title = "Сказочный мир"
version = "1.0.0"
id = "artifacts/skazki"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22197

[services.development]
run = "pnpm --filter @workspace/skazki run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/skazki", "run", "build" ]
publicDir = "artifacts/skazki/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22197"
BASE_PATH = "/"
